#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Author  : Xiaobo Yang
@Contact : hal_42@zju.edu.cn
@Time    : 2024/5/12 18:40
@File    : obj_names.py
@Software: PyCharm
@Desc    : 
"""
from alchemy_cat.py_tools import Config

cfg = config = Config()

cfg.es_fg_names = ['person with clothes,people,human', 'bicycle', 'car', 'motorbike', 'aeroplane',
                   'bus', 'train', 'truck', 'boat', 'traffic light',
                   'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird avian',
                   'cat', 'dog', 'horse', 'sheep', 'cow',
                   'elephant', 'bear', 'zebra', 'giraffe', 'backpack,bag',
                   'umbrella,parasol', 'handbag,purse', 'necktie', 'suitcase', 'frisbee',
                   'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat',
                   'glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle',
                   'wine glass', 'cup', 'fork', 'knife', 'spoon dessertspoon',
                   'bowl', 'banana', 'apple', 'sandwich', 'orange',
                   'broccoli', 'carrot', 'hot dog', 'pizza', 'donut',
                   'cake', 'chair seat', 'sofa', 'pottedplant', 'bed',
                   'diningtable', 'toilet', 'tvmonitor screen', 'laptop', 'mouse',
                   'remote control', 'keyboard', 'cell phone', 'microwave', 'oven',
                   'toaster', 'sink', 'refrigerator', 'book', 'clock',
                   'vase', 'scissors', 'teddy bear', 'hairdrier,blowdrier', 'toothbrush',
                   ]

cfg.es_bg_names = ['ground', 'land', 'grass', 'tree', 'building', 'wall', 'sky', 'lake', 'water', 'river', 'sea',
                   'railway', 'railroad', 'helmet',
                   'cloud', 'house', 'mountain', 'ocean', 'road', 'rock', 'street', 'valley', 'bridge',
                   ]  # 相比VOC，去掉了keyboard和sign。

cfg.sclip_fg_names = ['person, person in shirt, person in jeans, person in dress, '
                      'person in sweater, person in skirt, person in jacket, body',
                      'bicycle',
                      'car',
                      'motorcycle',
                      'airplane',
                      'bus',
                      'train',
                      'truck',
                      'boat',
                      'traffic light',
                      'fire hydrant',
                      'stop sign',
                      'parking meter',
                      'bench',
                      'bird',
                      'cat',
                      'dog',
                      'horse',
                      'sheep',
                      'cow',
                      'elephant',
                      'bear',
                      'zebra',
                      'giraffe',
                      'backpack',
                      'umbrella',
                      'handbag',
                      'tie',
                      'suitcase',
                      'frisbee',
                      'skis',
                      'snowboard',
                      'sports ball',
                      'kite',
                      'baseball bat',
                      'baseball glove',
                      'skateboard',
                      'surfboard',
                      'tennis racket',
                      'bottle',
                      'wine glass',
                      'cup',
                      'fork',
                      'knife',
                      'spoon',
                      'bowl',
                      'banana',
                      'apple',
                      'sandwich',
                      'orange',
                      'broccoli',
                      'carrot',
                      'hot dog',
                      'pizza',
                      'donut',
                      'cake',
                      'chair',
                      'couch',
                      'potted plant',
                      'bed',
                      'dining table',
                      'toilet',
                      'tv',
                      'laptop',
                      'mouse',
                      'remote',
                      'keyboard',
                      'cell phone',
                      'microwave',
                      'oven',
                      'toaster',
                      'sink',
                      'refrigerator',
                      'book',
                      'clock',
                      'vase',
                      'scissors',
                      'teddy bear',
                      'hair drier',
                      'toothbrush']

cfg.sclip_bg_names = ['sky',
                      'wall',
                      'tree',
                      'wood',
                      'grass',
                      'road',
                      'sea',
                      'river',
                      'mountain',
                      'sands',
                      'desk',
                      'bed',
                      'building',
                      'cloud',
                      'lamp',
                      'door',
                      'window',
                      'wardrobe',
                      'ceiling',
                      'shelf',
                      'curtain',
                      'stair',
                      'floor',
                      'hill',
                      'rail',
                      'fence']
